### ISSUE TITLE
Notifications about CRUD operations of the entity are in the feminine gender

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-framework/jmix#1947] opened 2023-06-28 06:48 UTC
jmix version 2.0.999-SNAPSHOT

Case:
* Add Ru locale
* Create/update/delete an entity

AR: 
![image](https://github.com/jmix-framework/jmix/assets/73226373/8d87d7b1-73b0-4287-b0b3-b47709980b9d)
ER: not sure, maybe `сохранен(а)`

For QA: check also entity without instance name

**Comment by konyashkina** [comment] 2023-06-28 07:44
It also affects notification texts in commercial add-ons: 
in Business calendar
![messageRUlocaleBC](https://github.com/jmix-framework/jmix/assets/85500330/6465d431-0539-48e1-8e12-c700c7af7782)

in BPM
![messageRUlocaleBPM](https://github.com/jmix-framework/jmix/assets/85500330/758d0efc-4555-4c36-b7a9-d18b8d8989f9)

**Comment by KremnevDmitry** [comment] 2023-12-15 08:32
Can't reproduce:
![image](https://github.com/jmix-framework/jmix/assets/75516667/d9c5655a-807e-4653-b2e2-dceaf1bfd818)

Probably fixed by: #2098

**Closed** 2023-12-27 08:25 UTC
Labels: state: can't reproduce, in: translations, in: flowui
