### ISSUE TITLE
GroupTable produces Exceptions when StyleProvider installed and grouping performed 

### ISSUE THREAD

**Issue by dominikblei** [jmix-framework/jmix#874] opened 2022-07-22 08:59 UTC
Scenario:
- Given a `GroupTable`
- A StyleProvider is installed via `@Install(to = <groupTableName>, subject = "styleProvider")`
- Grouping is performed in the Group Table

This leads to (100% reproducible):
```
ERROR 1 --- [ntContainer#4-1] io.jmix.ui.component.impl.AbstractTable  : Uncaught exception in Table StyleProvider
at io.jmix.core.common.util.Preconditions.checkNotNullArgument(Preconditions.java:101) ~[jmix-core-1.2.3.jar!/:na]
at io.jmix.ui.model.impl.CollectionContainerImpl.getItemIndex(CollectionContainerImpl.java:126) ~[jmix-ui-1.2.3.jar!/:na]
at io.jmix.ui.model.impl.CollectionContainerImpl.getItemOrNull(CollectionContainerImpl.java:120) ~[jmix-ui-1.2.3.jar!/:na]
at io.jmix.ui.component.data.table.ContainerTableItems.getItem(ContainerTableItems.java:96) ~[jmix-ui-1.2.3.jar!/:na]
at io.jmix.ui.component.impl.AbstractTable.getGeneratedCellStyle(AbstractTable.java:1330) ~[jmix-ui-1.2.3.jar!/:na]
at io.jmix.ui.component.impl.AbstractTable.generateCellStyle(AbstractTable.java:3154) ~[jmix-ui-1.2.3.jar!/:na]
at io.jmix.ui.component.impl.AbstractTable$StyleGeneratorAdapter.getStyle(AbstractTable.java:3342) ~[jmix-ui-1.2.3.jar!/:na]
at io.jmix.ui.widget.JmixGroupTable.paintGroupAggregation(JmixGroupTable.java:461) ~[jmix-ui-1.2.3.jar!/:na]
at io.jmix.ui.widget.JmixGroupTable.paintRowAttributes(JmixGroupTable.java:416) ~[jmix-ui-1.2.3.jar!/:na]
at com.vaadin.v7.ui.Table.paintRowAttributes(Table.java:4072) ~[vaadin-compatibility-server-8.14.1-1-jmix.jar!/:8.14.1-1-jmix]
at com.vaadin.v7.ui.Table.paintRow(Table.java:3957) ~[vaadin-compatibility-server-8.14.1-1-jmix.jar!/:8.14.1-1-jmix]
at com.vaadin.v7.ui.Table.paintRows(Table.java:3787) ~[vaadin-compatibility-server-8.14.1-1-jmix.jar!/:8.14.1-1-jmix]
at com.vaadin.v7.ui.Table.doPaintContent(Table.java:3365) ~[vaadin-compatibility-server-8.14.1-1-jmix.jar!/:8.14.1-1-jmix]
at com.vaadin.v7.ui.Table.paintContent(Table.java:3331) ~[vaadin-compatibility-server-8.14.1-1-jmix.jar!/:8.14.1-1-jmix]
at io.jmix.ui.widget.JmixTable.paintContent(JmixTable.java:1110) ~[jmix-ui-1.2.3.jar!/:na]
at io.jmix.ui.widget.JmixGroupTable.paintContent(JmixGroupTable.java:92) ~[jmix-ui-1.2.3.jar!/:na]
at com.vaadin.server.LegacyPaint.paint(LegacyPaint.java:65) ~[vaadin-server-8.14.1-1-jmix.jar!/:8.14.1-1-jmix]
at com.vaadin.server.communication.LegacyUidlWriter.write(LegacyUidlWriter.java:82) ~[vaadin-server-8.14.1-1-jmix.jar!/:8.14.1-1-jmix]
at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:158) ~[vaadin-server-8.14.1-1-jmix.jar!/:8.14.1-1-jmix]
at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:164) ~[vaadin-server-8.14.1-1-jmix.jar!/:8.14.1-1-jmix]
at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:142) ~[vaadin-server-8.14.1-1-jmix.jar!/:8.14.1-1-jmix]
at com.vaadin.ui.UI.push(UI.java:1708) ~[vaadin-server-8.14.1-1-jmix.jar!/:8.14.1-1-jmix]
at com.vaadin.server.VaadinSession.unlock(VaadinSession.java:1018) ~[vaadin-server-8.14.1-1-jmix.jar!/:8.14.1-1-jmix]
at com.vaadin.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:2055) ~[vaadin-server-8.14.1-1-jmix.jar!/:8.14.1-1-jmix]
at com.vaadin.server.VaadinService.accessSession(VaadinService.java:2021) ~[vaadin-server-8.14.1-1-jmix.jar!/:8.14.1-1-jmix]
at com.vaadin.server.VaadinSession.access(VaadinSession.java:1409) ~[vaadin-server-8.14.1-1-jmix.jar!/:8.14.1-1-jmix]
at com.vaadin.ui.UI.access(UI.java:1572) ~[vaadin-server-8.14.1-1-jmix.jar!/:8.14.1-1-jmix]
at io.jmix.ui.executor.impl.WebBackgroundWorker$WebUIAccessor.access(WebBackgroundWorker.java:433) ~[jmix-ui-1.2.3.jar!/:na]
[...] calling method from production code
```
The root cause appears to be in JmixGroupTable.java:461:
`String cellStyle = getCellStyleGenerator().getStyle(this, null, columnId);`
Observe that the second argument (`itemId`) is a hard-coded `null`, which later leads to the described exception.

**Comment by glebfox** [comment] 2022-08-01 12:26
Can't reproduce the issue with the exact steps. According to this line
```
at io.jmix.ui.widget.JmixGroupTable.paintGroupAggregation(JmixGroupTable.java:461) ~[jmix-ui-1.2.3.jar!/:na]
```
I assume that this issue is a duplicate of https://github.com/jmix-framework/jmix/issues/875

**Closed by glebfox** 2022-08-01 12:26 UTC
Labels: type: bug, size: S, in: ui
