### ISSUE TITLE
Reopening the file does not work

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2426] opened 2023-11-01 08:45 UTC
look #2402

Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5686-232
IntelliJ version: IntelliJ IDEA 2023.2.4 (Ultimate Edition)

If you do not save the authorization settings when opening the file for the first time, then you will not be able to reopen the file

**Comment by Gavrilov-Ivan** [comment] 2023-11-13 08:40
This problem is caused by warning message about future unsupport of basic auth.
Marking it as 'do not show again' ruins further working with WebDAV documents. 
Root cause is unknown.

WA - undo 'do not show again' checkbox in registry:
set value of `BasicAuthSuppressWarning` to '0' (path: HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\Common\Identity)

https://answers.microsoft.com/en-us/msoffice/forum/all/warning-message-that-in-future-versions-basic/e33cf6e3-8be4-41e3-897a-510894f803cf

**Closed** 2023-11-24 07:35 UTC
Labels: type: bug, in: webdav
