### ISSUE TITLE
Data missed when clicked "Search" on Filter with autoApply=false

### ISSUE THREAD

**Issue by Flamesson** [jmix-framework/jmix#788] opened 2022-06-23 09:19 UTC
Preconditions:
- I have a Table in a screen. It is bounded to a CollectionContainer
- I also have a Filter with autoApply = false
- Have a pagination

When select 2-nd page of pagination and enter some condition such way to select an entity from the first page to the filter pagination becomes broken and nothing is found. It was expected that will have only one page in pagination and the page will be selected.

This happens because firstResult of Filter.loader is not set to 0. When autoApply is true - Filter.apply sets firstResult=0

**My sample project:** https://github.com/izumi-jmix/filter-and-pagination

**Screenshots:**

- First page of pagination. My target - an Employee with first name "f2" and last name "l2"

![image](https://user-images.githubusercontent.com/51899225/175266613-8d163ef2-92b1-4692-a359-0a12a5b56825.png)

- Second page with added condition. "Search" is not clicked yet

![image](https://user-images.githubusercontent.com/51899225/175267070-4b9c34da-c50e-442e-903b-abcdcfc746d1.png)

- The "Search" was clicked

![image](https://user-images.githubusercontent.com/51899225/175267143-245c71e5-13fc-4140-847b-fed813282f38.png)

**My debug results (HSQL):**

When autoApply=false query: 
_SELECT LIMIT ? ? ID AS a1, FIRST_NAME AS a2, LAST_NAME AS a3 FROM EMPLOYEE WHERE LOWER(LAST_NAME) LIKE ?_
bind => [10, 10, %l2%]

When autoApply=true query:
_SELECT LIMIT ? ? ID AS a1, FIRST_NAME AS a2, LAST_NAME AS a3 FROM EMPLOYEE WHERE LOWER(LAST_NAME) LIKE ?_
bind => [0, 10, %l2%]

**Comment by dtaimanov** [comment] 2022-07-08 15:33
Duplicate of #802

**Closed** 2022-07-08 15:34 UTC
Labels: size: S
