### ISSUE TITLE
Performance problem if autogenerated UUID field is not a primary key

### ISSUE THREAD

**Issue by fractal3000** [jmix-framework/jmix#3872] opened 2024-11-14 20:47 UTC
### Environment

Jmix version: 1.5.0

### Bug Description

There is a problem if the primary key of anу entity is of the Long data type and the the entity has another autogenerated UUID field.
In this case the Entity fetcher calls the "hashCode()"method that in turn uses uuid field that is not loaded with fetch plan. Such there is two consecuent problems:
1. A lot of queries to database to get the "uuid" field
2. As a consecuence of the reloading of the entity the all another fields except "uuid" are going to be empy. So when we get access to them the application generate a lot of queries to get data of these fields.

### Steps To Reproduce

1. Open and run the attached sample project with profiler.
2. Open the screen with the "Load screen name"
3. Click the "Load" button

### Current Behavior

There are 6000 queries to DB

### Expected Behavior

There are 1000 queries to DB

### Sample Project
[genId_1_5.zip](https://github.com/user-attachments/files/17757615/genId_1_5.zip)

Profiler screenshots
![image](https://github.com/user-attachments/assets/b7ce6ee5-37f3-4eea-b859-3b497268720a)
![image](https://github.com/user-attachments/assets/fcc3f658-538c-48da-be68-02aaec59ecae)

**Comment by knstvk** [comment] 2024-11-15 07:27
Check in 1.6 too

**Comment by dtaimanov** [comment] 2024-11-15 15:22
Duplicate of https://github.com/jmix-framework/jmix/issues/1774

**Closed by dtaimanov** 2024-11-15 15:22 UTC
Labels: type: bug, size: M, in: data
